({
	setupCurrencies: function (component, event, helper) {
         var opts = [
                { class: "optionClass", label: "Algerian Dinar (DZD)", value: "DZD" },
                { class: "optionClass", label: "Argentine Peso (ARS)", value: "ARS" },
                { class: "optionClass", label: "Australian Dollar (A$)", value: "AUD" },
                { class: "optionClass", label: "Bahraini Dinar (BHD)", value: "BHD" },
                { class: "optionClass", label: "Bangladeshi Taka (BDT)", value: "BDT" },
                { class: "optionClass", label: "Bolivian Boliviano (BOB)", value: "BOB" },
                { class: "optionClass", label: "Botswanan Pula (BWP)", value: "BWP" },
                { class: "optionClass", label: "Brazilian Real (R$)", value: "BRL" },
                { class: "optionClass", label: "British Pound Sterling (£)", value: "GBP" },
                { class: "optionClass", label: "Brunei Dollar (BND)", value: "BND" },
                { class: "optionClass", label: "Bulgarian Lev (BGN)", value: "BGN" },
                { class: "optionClass", label: "Canadian Dollar (CA$)", value: "CAD" },
                { class: "optionClass", label: "Cayman Islands Dollar (KYD)", value: "KYD" },
                { class: "optionClass", label: "CFA Franc BCEAO (CFA)", value: "XOF" },
                { class: "optionClass", label: "Chilean Peso (CLP)", value: "CLP" },
                { class: "optionClass", label: "Chinese Yuan (CN¥)", value: "CNY" },
                { class: "optionClass", label: "Colombian Peso (COP)", value: "COP" },
                { class: "optionClass", label: "Costa Rican Colon (CRC)", value: "CRC" },
                { class: "optionClass", label: "Croatian Kuna (HRK)", value: "HRK" },
                { class: "optionClass", label: "Czech Republic Koruna (CZK)", value: "CZK" },
                { class: "optionClass", label: "Danish Krone (DKK)", value: "DKK" },
                { class: "optionClass", label: "Dominican Peso (DOP)", value: "DOP" },
                { class: "optionClass", label: "Egyptian Pound (EGP)", value: "EGP" },
                { class: "optionClass", label: "Estonian Kroon (EEK)", value: "EEK" },
                { class: "optionClass", label: "Euro (€)", value: "EUR" },
                { class: "optionClass", label: "Fijian Dollar (FJD)", value: "FJD" },
                { class: "optionClass", label: "Honduran Lempira (HNL)", value: "HNL" },
                { class: "optionClass", label: "Hong Kong Dollar (HK$)", value: "HKD" },
                { class: "optionClass", label: "Hungarian Forint (HUF)", value: "HUF" },
                { class: "optionClass", label: "Indian Rupee (₹)", value: "INR" },
                { class: "optionClass", label: "Indonesian Rupiah (IDR)", value: "IDR" },
                { class: "optionClass", label: "Israeli New Sheqel (₪)", value: "ILS" },
                { class: "optionClass", label: "Jamaican Dollar (JMD)", value: "JMD" },
                { class: "optionClass", label: "Japanese Yen (¥‎)", value: "JPY" },
                { class: "optionClass", label: "Jordanian Dinar (JOD)", value: "JOD" },
                { class: "optionClass", label: "Kazakhstani Tenge (KZT)", value: "KZT" },
                { class: "optionClass", label: "Kenyan Shilling (KES)", value: "KES" },
                { class: "optionClass", label: "Kuwaiti Dinar (KWD)", value: "KWD" },
                { class: "optionClass", label: "Latvian Lats (LVL)", value: "LVL" },
                { class: "optionClass", label: "Lebanese Pound (LBP)", value: "LBP" },
                { class: "optionClass", label: "Lithuanian Litas (LTL)", value: "LTL" },
                { class: "optionClass", label: "Macedonian Denar (MKD)", value: "MKD" },
                { class: "optionClass", label: "Malaysian Ringgit (MYR)", value: "MYR" },
                { class: "optionClass", label: "Maldivian Rufiyaa (MVR)", value: "MVR" },
                { class: "optionClass", label: "Mauritian Rupee (MUR)", value: "MUR" },
                { class: "optionClass", label: "Mexican Peso (MX$)", value: "MXN" },
                { class: "optionClass", label: "Moldovan Leu (MDL)", value: "MDL" },
                { class: "optionClass", label: "Moroccan Dirham (MAD)", value: "MAD" },
                { class: "optionClass", label: "Namibian Dollar (NAD)", value: "NAD" },
                { class: "optionClass", label: "Nepalese Rupee (NPR)", value: "NPR" },
                { class: "optionClass", label: "Netherlands Antillean Guilder (ANG)", value: "ANG" },
                { class: "optionClass", label: "New Taiwan Dollar (NT$)", value: "TWD" },
                { class: "optionClass", label: "New Zealand Dollar (NZ$)", value: "NZD" },
                { class: "optionClass", label: "Nicaraguan Córdoba (NIO)", value: "NIO" },
                { class: "optionClass", label: "Nigerian Naira (NGN)", value: "NGN" },
                { class: "optionClass", label: "Norwegian Krone (NOK)", value: "NOK" },
                { class: "optionClass", label: "Omani Rial (OMR)", value: "OMR" },
                { class: "optionClass", label: "Pakistani Rupee (PKR)", value: "PKR" },
                { class: "optionClass", label: "Papua New Guinean Kina (PGK)", value: "PGK" },
                { class: "optionClass", label: "Paraguayan Guarani (PYG)", value: "PYG" },
                { class: "optionClass", label: "Peruvian Nuevo Sol (PEN)", value: "PEN" },
                { class: "optionClass", label: "Philippine Peso (Php)", value: "PHP" },
                { class: "optionClass", label: "Polish Zloty (PLN)", value: "PLN" },
                { class: "optionClass", label: "Qatari Rial (QAR)", value: "QAR" },
                { class: "optionClass", label: "Romanian Leu (RON)", value: "RON" },
                { class: "optionClass", label: "Russian Ruble (RUB)", value: "RUB" },
                { class: "optionClass", label: "Salvadoran Colon (SVC)", value: "SVC" },
                { class: "optionClass", label: "Saudi Riyal (SAR)", value: "SAR" },
                { class: "optionClass", label: "Serbian Dinar (RSD)", value: "RSD" },
                { class: "optionClass", label: "Seychellois Rupee (SCR)", value: "SCR" },
                { class: "optionClass", label: "Sierra Leonean Leone (SLL)", value: "SLL" },
                { class: "optionClass", label: "Singapore Dollar (SGD)", value: "SGD" },
                { class: "optionClass", label: "Slovak Koruna (SKK)", value: "SKK" },
                { class: "optionClass", label: "South African Rand (ZAR)", value: "ZAR" },
                { class: "optionClass", label: "South Korean Won (₩)", value: "KRW" },
                { class: "optionClass", label: "Sri Lankan Rupee (LKR)", value: "LKR" },
                { class: "optionClass", label: "Swedish Krona (SEK)", value: "SEK" },
                { class: "optionClass", label: "Swiss Franc (CHF)", value: "CHF" },
                { class: "optionClass", label: "Tanzanian Shilling (TZS)", value: "TZS" },
                { class: "optionClass", label: "Thai Baht (฿)", value: "THB" },
                { class: "optionClass", label: "Trinidad and Tobago Dollar (TTD)", value: "TTD" },
                { class: "optionClass", label: "Tunisian Dinar (TND)", value: "TND" },
                { class: "optionClass", label: "Turkish Lira (TRY)", value: "TRY" },
                { class: "optionClass", label: "Ugandan Shilling (UGX)", value: "UGX" },
                { class: "optionClass", label: "Ukrainian Hryvnia (UAH)", value: "UAH" },
                { class: "optionClass", label: "United Arab Emirates Dirham (AED)", value: "AED" },
                { class: "optionClass", label: "Uruguayan Peso (UYU)", value: "UYU" },
                { class: "optionClass", label: "US Dollar ($)", value: "USD" },
                { class: "optionClass", label: "Uzbekistan Som (UZS)", value: "UZS" },
                { class: "optionClass", label: "Venezuelan Bolívar (VEF)", value: "VEF" },
                { class: "optionClass", label: "Vietnamese Dong (₫)", value: "VND" },
                { class: "optionClass", label: "Yemeni Rial (YER)", value: "YER" },
                { class: "optionClass", label: "Zambian Kwacha (ZMK)", value: "ZMK" }
            ];	

	    component.find("fromCurrencyList").set("v.options", opts);
        component.find("toCurrencyList").set("v.options", opts);
	},
    invokeConversion: function(component, event, helper) {
        helper.getConvertedAmount(component, component.get("v.amount"), component.get("v.fromCurrency"), component.get("v.toCurrency"));
    }
})